// note, these are copied from the main loaded page of the seeded development environment
window.fixtures = {
  accounting_transactions: [
    {"id":1,"date_time":"2012-01-01T10:05:00Z","income_expense":"income","amount":2198,"category_key":"2","account_key":"2","note":"verify in checking","invoice_id":null,"receivable_id":null},{"id":2,"date_time":"2012-01-02T11:32:00Z","income_expense":"expense","amount":100000,"category_key":"4","account_key":"2","note":"Jan 2012","invoice_id":null,"receivable_id":null},{"id":3,"date_time":"2012-01-03T13:03:00Z","income_expense":"expense","amount":3312,"category_key":"3","account_key":"1","note":"business cards","invoice_id":null,"receivable_id":null},{"id":4,"date_time":"2012-01-03T16:18:00Z","income_expense":"income","amount":6100,"category_key":"4","account_key":"2","note":"sent to insurance on 1/5/2012","invoice_id":3,"receivable_id":4},{"id":5,"date_time":"2012-01-03T16:18:00Z","income_expense":"income","amount":1100,"category_key":"1","account_key":"1","note":"only had cash","invoice_id":3,"receivable_id":null}
  ],
  option_selectors: [
    {"id":1,"name":"accounting_credit_debit"},{"id":2,"name":"accounting_category_expense"},{"id":3,"name":"accounting_category_income"},{"id":4,"name":"accounting_account"},{"id":5,"name":"identity_types"},{"id":6,"name":"product_service"}
  ],
  option_selector_options: [
    {"option_selector_id":1,"key":"1","value":"Credit","default_price":null},{"option_selector_id":1,"key":"2","value":"Debit","default_price":null},{"option_selector_id":2,"key":"1","value":"Advertising","default_price":null},{"option_selector_id":2,"key":"2","value":"Equipment","default_price":null},{"option_selector_id":2,"key":"3","value":"Office Supplies","default_price":null},{"option_selector_id":2,"key":"4","value":"Rent","default_price":null},{"option_selector_id":2,"key":"5","value":"Utilities","default_price":null},{"option_selector_id":2,"key":"blank","value":"","default_price":null},{"option_selector_id":2,"key":"cancel","value":"Cancel","default_price":null},{"option_selector_id":3,"key":"1","value":"Cash Payment","default_price":null},{"option_selector_id":3,"key":"2","value":"Credit Card Payment","default_price":null},{"option_selector_id":3,"key":"3","value":"Check Payment","default_price":null},{"option_selector_id":3,"key":"4","value":"Insurance Payment","default_price":null},{"option_selector_id":3,"key":"blank","value":"","default_price":null},{"option_selector_id":3,"key":"cancel","value":"Cancel","default_price":null},{"option_selector_id":4,"key":"1","value":"Cash Reserves","default_price":null},{"option_selector_id":4,"key":"2","value":"Business Checking","default_price":null},{"option_selector_id":4,"key":"3","value":"Business Savings","default_price":null},{"option_selector_id":4,"key":"blank","value":"","default_price":null},{"option_selector_id":4,"key":"cancel","value":"Cancel","default_price":null},{"option_selector_id":5,"key":"1","value":"Prospective Client","default_price":null},{"option_selector_id":5,"key":"2","value":"Practice Member","default_price":null},{"option_selector_id":5,"key":"3","value":"Insurance Company","default_price":null},{"option_selector_id":5,"key":"4","value":"Practitioner","default_price":null},{"option_selector_id":5,"key":"5","value":"Practice Personnel","default_price":null},{"option_selector_id":6,"key":"1","value":"Introductory Package","default_price":15000},{"option_selector_id":6,"key":"2","value":"Entrainment","default_price":5000},{"option_selector_id":6,"key":"3","value":"SRI Session","default_price":4000},{"option_selector_id":6,"key":"4","value":"10 Visit Package","default_price":45000},{"option_selector_id":6,"key":"5","value":"Herbs/Vitamins","default_price":2995},{"option_selector_id":6,"key":"6","value":"Homeopathic Remedies","default_price":599},{"option_selector_id":6,"key":"blank","value":"","default_price":null},{"option_selector_id":6,"key":"cancel","value":"Cancel","default_price":null}
  ]
}
