// note, these are copied from the main loaded page of the seeded development environment
window.fixtures = {
  accounting_transactions: [
{"id":1,"date_time":"2012-01-01T10:05:00Z","income_expense":"income","amount":2198,"category_id":9,"account_id":15,"note":"verify in checking","invoice_id":null,"receivable_id":null},{"id":2,"date_time":"2012-01-02T11:32:00Z","income_expense":"expense","amount":100000,"category_id":4,"account_id":15,"note":"Jan 2012","invoice_id":null,"receivable_id":null},{"id":3,"date_time":"2012-01-03T13:03:00Z","income_expense":"expense","amount":3312,"category_id":3,"account_id":14,"note":"business cards","invoice_id":null,"receivable_id":null},{"id":4,"date_time":"2012-01-03T16:18:00Z","income_expense":"income","amount":6100,"category_id":11,"account_id":15,"note":"sent to insurance on 1/5/2012","invoice_id":3,"receivable_id":4},{"id":5,"date_time":"2012-01-03T16:18:00Z","income_expense":"income","amount":1100,"category_id":8,"account_id":14,"note":"only had cash","invoice_id":3,"receivable_id":null}
  ],

  option_selectors: [
{"id":1,"name":"accounting_category_expense"},{"id":2,"name":"accounting_category_income"},{"id":3,"name":"accounting_account"},{"id":4,"name":"identity_types"},{"id":5,"name":"product_service"}
  ],
  option_selector_options: [
{"id":1,"option_selector_id":1,"value":"Advertising","default_price":null},{"id":2,"option_selector_id":1,"value":"Equipment","default_price":null},{"id":3,"option_selector_id":1,"value":"Office Supplies","default_price":null},{"id":4,"option_selector_id":1,"value":"Rent","default_price":null},{"id":5,"option_selector_id":1,"value":"Utilities","default_price":null},{"id":6,"option_selector_id":1,"value":"","default_price":null},{"id":7,"option_selector_id":1,"value":"Cancel","default_price":null},{"id":8,"option_selector_id":2,"value":"Cash Payment","default_price":null},{"id":9,"option_selector_id":2,"value":"Credit Card Payment","default_price":null},{"id":10,"option_selector_id":2,"value":"Check Payment","default_price":null},{"id":11,"option_selector_id":2,"value":"Insurance Payment","default_price":null},{"id":12,"option_selector_id":2,"value":"","default_price":null},{"id":13,"option_selector_id":2,"value":"Cancel","default_price":null},{"id":14,"option_selector_id":3,"value":"Cash Reserves","default_price":null},{"id":15,"option_selector_id":3,"value":"Business Checking","default_price":null},{"id":16,"option_selector_id":3,"value":"Business Savings","default_price":null},{"id":17,"option_selector_id":3,"value":"","default_price":null},{"id":18,"option_selector_id":3,"value":"Cancel","default_price":null},{"id":19,"option_selector_id":4,"value":"Prospective Client","default_price":null},{"id":20,"option_selector_id":4,"value":"Practice Member","default_price":null},{"id":21,"option_selector_id":4,"value":"Insurance Company","default_price":null},{"id":22,"option_selector_id":4,"value":"Practitioner","default_price":null},{"id":23,"option_selector_id":4,"value":"Practice Personnel","default_price":null},{"id":24,"option_selector_id":5,"value":"Introductory Package","default_price":15000},{"id":25,"option_selector_id":5,"value":"Entrainment","default_price":5000},{"id":26,"option_selector_id":5,"value":"SRI Session","default_price":4000},{"id":27,"option_selector_id":5,"value":"10 Visit Package","default_price":45000},{"id":28,"option_selector_id":5,"value":"Herbs/Vitamins","default_price":2995},{"id":29,"option_selector_id":5,"value":"Homeopathic Remedies","default_price":599},{"id":30,"option_selector_id":5,"value":"","default_price":null},{"id":31,"option_selector_id":5,"value":"Cancel","default_price":null}
  ]
}
